[package]
name = "of-vscode-project-generator-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
argparse = "0.2.2"
env_logger = "0.11.8"
log = "0.4.27"
once_cell = "1.21.3"
serde_json = "1.0.142"
